### ISSUE TITLE
Way to paginate polling trigger

### ISSUE THREAD

**Issue by drinchev** [zapier/zapier-platform-cli#131]
I'm having trouble enabling pagination of triggers that are polling based.

I was not able to find anything in the docs suggesting how is `bundle.meta.page` modified.

Related issue : https://github.com/zapier/zapier-platform-core/issues/42

I'm expecting to be able to create a trigger that will paginate until the first duplicate of id is encountered. 

So far I tried adding `canPaginate: true` on my trigger definition, but it seems that this switch doesn't do anything.

Thanks for your help.

**Comment by bcooksey** [comment]
Hey @drinchev, you are correct that the `canPaginate: true` flag doesn't affect polling of live Zaps. It's used in cases where the trigger powers a dynamic dropdown and we want to know if we should show a "Load More" button in the dropdown to fetch another page. Agree that the terminology there is a little confusing.

To give you an idea of the expected mode of operation for triggers, Zapier is going to poll every 5-15 minutes looking for new results. For vast majority of cases we see, a single page has more then enough results for us to detect everything new since the last time we polled, so it should be ok to let us just grab one page of the most recently created items.
