### ISSUE TITLE
Environment improvements

### ISSUE THREAD

**Issue by xavdid** [zapier/zapier-platform-cli#16]
A couple of tweaks could be cool:

1. It would be great if the version number were optional and defaulted to the most recent version. Especially when adding new variables, which is pretty safe (editing and removing less so)
2. `zapier env 1.0.0` gives an error before `1.0.0` is registered- this makes sense. However, it seems counterintuitive to push a version before required variables are set (say, an API key). Not sure what the best course here is, maybe encouraging to publish right away? Or `register` pushes a `0.0.0` just to push against? 
3. One of my favorite heroku features (so much so that I [wrote](https://github.com/xavdid/heroku-config) the most recent version of it) is the ability to sync the env to and from the platform. Similar functionality would be a nice-to-have for sure!

**Comment by BrunoBernardino** [comment]
Cleaning up issues!

1. I like asking for the version, to make sure the dev is aware of it, and I can also see how not typing it could be useful/faster. While I'm open to making it default to the most recent version (that's been pushed), it requires some more code I'm not sure adds that much more value.
2. The `push` here doesn't have the app be used right away, so I think the two-step process makes sense. I don't like the idea of an "empty" `0.0.0`, and this workflow hasn't been raised as a problem before.
3. Similarly to 1, I can see it being a nice thing to have, but more code and not necessarily a lot of value.

Since none of this has been brought up in over a year, I'd say it's safe to close this issue, but happy to reconsider if there's any more information/data I'm not aware of.
