### ISSUE TITLE
Conditional requires

### ISSUE THREAD

**Issue by xavdid** [zapier/zapier-platform-cli#17]
It's nice to conditionally `require()` modules like so:

```javascript
if (process.env.NODE_ENV !== 'production' && !process.env.RIOT_API_KEY) {
  require('dotenv').load()
}
```
produces the following error:
```
Error: Cannot find module 'dotenv' from '/private/var/folders/dg/c2gwj6zx2n9_9zxsb4typ63m0000gn/T/zapier-a5d3418b'
    at /Users/david/.nvm/versions/node/v6.6.0/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:46:17
    at process (/Users/david/.nvm/versions/node/v6.6.0/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/david/.nvm/versions/node/v6.6.0/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/david/.nvm/versions/node/v6.6.0/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/david/.nvm/versions/node/v6.6.0/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:92:31)
    at /Users/david/.nvm/versions/node/v6.6.0/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I realize this specific action can use `zapier.tools.env.inject()`, but it's still sometimes a useful pattern for testing

**Comment by bryanhelmig** [comment]
Hmm, I think as long as `dotenv` is in packages.json it includes it in the build, regardless of if the `require()` is behind a switch or not (as long as the first argument into `require()` is a string literal).

**Comment by xavdid** [comment]
does it need to be in `dependencies` vs `devDependencies`?

**Comment by bryanhelmig** [comment]
For context - we copy the code to a temp directory, run `npm install`, then do some validation (which includes running your code) and zip up that temp directory. So if your code validation depends on some package, it needs to be in `dependencies` - yes.

However, maybe there is some weirdness with environment inheriting or your current environment for child build processes. Are you doing something like?

```
$ NODE_ENV=production RIOT_API_KEY="" zapier push
```

Because if you are effectively doing:

```
$ export NODE_ENV=debug
$ export RIOT_API_KEY=123456abcdef
$ zapier push
```

Then the build is probably still happening in your debug environment without `devDependencies`.

**Comment by bryanhelmig** [comment]
It seems like environment is proving tricky because we're trying to juggle lazy production environments with local environments for the build. Contrasted to Heroku, they don't care about your local environment once you push (because the build happens on their side).

Open to suggestions on helping clarify this - maybe we just need to bite the bullet and do "clean room" builds in the cloud. Lots of work though.

**Comment by BrunoBernardino** [comment]
Closing this over being a year old and not having caused any problems the way it is.
