### ISSUE TITLE
An Error thrown during an unsubscribe doesn't stop the Zap from being disabled

### ISSUE THREAD

**Issue by bmichelich** [zapier/zapier-platform-cli#261]
We have validation checks in the trigger during the subscribe and unsubscribe events.

If the response content doesn't have the expected values after enabling or disabling a zap, we are throwing an Error to prevent the Zap from changing state.

When an Error is thrown, the UI should show an error message.  This works for the subscribe hook but not for the unsubscribe hook and recently was working for both.

## What would you like to change?

When a user clicks on a zap's disable button
And the trigger raises an Error
Then the zapier zap UI should display an error message to the user
And the zap should not be disabled

## Your Environment

* CLI Version (`zapier -v`): 5.0.0
* Operating System and version:  N/A

**Comment by xavdid** [comment]
@bmichelich this definitely sounds like a bug! Can you talk a little bit more about what sort of validation you're performing? it seems like if a user is trying to turn off a zap, that should always happen.

**Comment by bmichelich** [comment]
We had a bug in our endpoint that failed to register or unregister a zapier hook.  I added a check on the response so if this happens in the future for whatever reason, the zapier UI would prevent the Zap from changing state.  This to prevent the zap being out of sync with the registered webhook.

It was working as expected until this morning.

**Comment by benzapier** [comment]
That's a great point - when turning on a Zap (and subscribing the Zap's webhook URL), if there's an error, then the Zap will remain "off", and the editor will (or should) display the error to the user.

If a user tries to turn "off" a Zap, and an error occurs during the unsubscribe process, our system will ignore the error (which isn't always the _ideal_ option), but then any future data that gets sent to the Zap's webhook URL will receive an `HTTP-410` (Gone) response, to notify the sender that there's no need to continue sending data to the webhook.

That's basically a fall-back/workaround for certain situations - like when a user's auth/token may have expired (or been revoked), and thus the unsubscribe fails, instead of raising an error to the user (who probably won't know how to resolve things).

If your system would like to periodically "ping" the subscribed webhooks, to see if they're still valid, pass over an empty JSON array, and see whether you receive a `200` or `410` resposne.

**Comment by bmichelich** [comment]
That makes sense.   In that case, this is working as designed.  Thanks.

**Comment by xavdid** [comment]
Cool, I'll close. thanks for bringing it up!
