### ISSUE TITLE
Paginate triggers dynamically

### ISSUE THREAD

**Issue by krve** [zapier/zapier-platform-cli#293]
I'm trying to paginate the response from a trigger. I've tried looking at: https://zapier.github.io/zapier-platform-cli/#is-it-possible-to-iterate-over-pages-in-a-polling-trigger.

In the second example, I don't understand the purpose of:
```javascript
if (results[0].id < 5) {
  response = await z.request({
    url: 'https://jsonplaceholder.typicode.com/posts',
    params: {
      _start: 3,
      _limit: 3
    }
  });

  results = results.concat(response.json);
}
```

*"Keep an eye on the polling guidelines, namely the part about only iterating until you hit items that have probably been seen in a previous poll."*

How do I check if i've seen that item in a previous poll? How do i change the `if (results[0].id < 5)` into something that actually checks if it has polled that item before?

**Comment by codekirei** [comment]
Hi! Great question. The condition `results[0].id < 5` in that example is completely contrived — I'll see if we can switch that to something more useful.

Unfortunately, our [general deduplication docs](https://zapier.com/developer/documentation/v2/deduplication/) still apply here, specifically in the sense that you don't have access to previously seen IDs when the trigger runs.

Since you can't check in the trigger logic whether any given ID has been seen before, the recommended approach is to approximate how many results you need to see to not miss results between 15 minute polls, and paginate to that number.

For example, let's say you think you need 100 results per poll, and your maximum page size is 30. You'd probably want to paginate through 4 total requests.

To do this, you'd need to set up your trigger to iterate through those pages, modifying params and potentially also checking if the response is indicating that there are any more records to get (and bailing if not) each time. You could do this with any standard iterating construct in JS.

**Comment by krve** [comment]
Would it be possible to move the burden server-side? So that our server is handling whether or not any new items have been added since the last request?

I'm asking because the amount of items that gets added between the 15 minute delay can be quite large. Sometimes 1000's of items, which I think would cause the trigger to exceed the 30 second delay.

**Comment by krve** [comment]
This would actually not really be possible because if you create multiple Zaps it would update when both Zaps make the request which is not what I want.

So my only choice is to make the poll large enough and *hope* that the items don't exceed the expected amount?

**Comment by xavdid** [comment]
The typical approach here is to filter the array you're going to return by created date (which is hopefully available). Polls run every 5-15 minutes, so if you return all items created in the last hour or two, you should be covered. Returning thousands of items is ok on our end (we can handle up to ~6MB of data, which is a fair amount of JSON). Hopefully that can be done in a few calls to your API. 

Anyway, this is not something we're considering as a FR. let us know if theres' anything else we can help with!
