### ISSUE TITLE
Make "fromVersion" optional for "zapier migrate"

### ISSUE THREAD

**Issue by ifedapoolarewaju** [zapier/zapier-platform-cli#331]
[We](https://transloadit.com) are trying to automate the deployment of new versions of our zapier app, and it'll be easier for us if we could run this command `zapier migrate [fromVersion] [toVersion]` without specifying the `fromVersion` so that it defaults to the previous latest version.

## Make fromVersion optional
currently we have to use the command `zapier versions` to automatically detect which versions are available to migrate from.
However, It'll be nice if the `fromVersion` is made optional, and the value defaults to the version right before the `toVersion`

**Comment by BrunoBernardino** [comment]
Thank you so much for this feature request @ifedapoolarewaju !

Wrong migrations can create problems for customers, so we try to make the process as intentional as possible. While we have a lot of checks to prevent incompatible migrations, it's not a flawless process.

With that in mind, I'm trying to understand your use case and see if there's an alternative here, like specifying `previous` and `latest` as special sugar syntax.

Would something like `zapier migrate previous 1.1.0` work for you?

Here's a couple of scenarios with version lists and what `previous` and `latest` would mean:

Scenario 1
```
1.0.1 - deprecated
1.1.4 - deprecated
1.1.5 - previous
1.2.0 - latest
```

Scenario 2
```
2.3.1
2.3.2 - previous
2.3.3 - latest
```

Does that look OK?

**Comment by xavdid** [comment]
Hi! Just wanted to circle back here. We've discussed this internally, and have decided to keep `fromVersion` a required property in the interest of being explicit. Since migrations can so easily break zaps for users, we want to make sure devs give thoughts to both versions that are involved in a migration. 

That said, `zapier versions` can return json that's easy enough to parse (if you feel the need to automate it). Just again, please be careful. 😁
