### ISSUE TITLE
Docs Improvement

### ISSUE THREAD

**Issue by bryanhelmig** [zapier/zapier-platform-cli#4]
We're missing quite a few documentation sections:

- [x] Dynamic dropdown fields
- [x] `z.errors` and their effects
- [x] general "error handling" guidance (it is common for folks to throw away the errors)
- [x] general description of standard "flow" for oauth 2
- [x] high level description of architecture (basically RPC into AWS Lambda)
- [x] REST hooks ([and example apps](https://github.com/zapier/zapier-platform-example-app-hook/pull/1))
- [x] Inline docs for schema need some love. https://github.com/zapier/zapier-platform-schema/pull/12
- [ ] In the basic example app, the test for “style” is weird because it still passes even if you nuke the param. The test should check the request object or something so that removing the bundle/param caused the test to fail
- [x] Update tutorial to use code snippets that match the breaking changes
- [x] Show example for usage of `dynamic` in `inputFields`
- [x] Show example for usage of `search` in `inputFields`
- [x] ~~~Show example for usage of `dict` in `inputFields`~~~ Can circle back to this when we decide if we want to give detailed docs for every option
- [x] converting v2 apps
- [ ] Maybe call out resources in the tutorial better so devs know they are there
- [ ] file example app 
- [x] The hosted docs at zapier.github.io have an issue with sub-navigation. Anything that contains a `/` or a `(` does not follow the anchor.

**Comment by pidov** [comment]
Using REST Hooks is also not documented, although it's supported.

**Comment by bryanhelmig** [comment]
Thanks for the reminder - added to the list @pidov!

I documented fields - as well as dynamic fields https://github.com/zapier/zapier-platform-cli#fields.

**Comment by xavdid** [comment]
How about more specifics about what version(s) are expected/needed.

I know the code is executed under node 4, but since babel is listed as a dev dep it's implied that I could develop my v3 app on whatever version of node I wanted and transpile it down to whatever AWS expects. Related, it'd be nice if the sample apps also had a build command in the `package.json`. 

For this repo, there's a `.nvmrc` that may not need to be there if the plugin itself doesn't need to be developed in `v4.3.2`.

**Comment by bcooksey** [comment]
Spun off an issue for the file example app https://github.com/zapier/zapier-platform-cli/issues/42
