### ISSUE TITLE
Mandatory `removeMissingValuesFrom` type definition in z.request object in zapier-platform-core

### ISSUE THREAD

**Issue by humphreybc** [zapier/zapier-platform-cli#405]
`removeMissingValuesFrom` is marked as a [mandatory field in the request object in the type definitions for zapier-platform-core](https://github.com/zapier/zapier-platform-core/blob/master/index.d.ts#L82). I'm not really sure what this does, but I'm pretty sure it shouldn't be mandatory since our app has been working okay without passing this parameter.

## What would you like to change?

Suggested change:

```
removeMissingValuesFrom?: {
  params: boolean,
  body: boolean,
};
```

## Your Environment

N/A

**Comment by xavdid** [comment]
Hey there! You're correct, that was erroneously marked as required (as noted in the [changelog](https://github.com/zapier/zapier-platform-cli/blob/master/CHANGELOG.md#core-1). The fix is already merged (https://github.com/zapier/zapier-platform-core/pull/143) and will go out in the next release.

You options for now are:

1. include `removeMissingValuesFrom: {}` in any `z.request` calls
2. stay on `7.6.1` until `8.0.2` is released

Both are perfectly valid. Sorry for the inconvenience!

**Comment by humphreybc** [comment]
@xavdid I don't think I can just pass an empty object since `params` and `body` are also marked as required in the type definition. What’s the default for these values? True or false?

**Comment by xavdid** [comment]
Ah, sorry about that. Default is both false.
