### ISSUE TITLE
Update based triggers

### ISSUE THREAD

**Issue by mnsami** [zapier/zapier-platform-cli#414]
I'm developing an integration with zapier and I have two questions:
**1. Update triggers**
https://zapier.com/developer/documentation/v2/planning-guide-v1/#update-triggers

But i can't find a documentation to develop such a trigger, I have been trying to think how to get this done, I read on https://platform.zapier.com/docs/triggers?utm_source=zapier.com&utm_medium=referral&utm_campaign=zapier#trigger-types

that I have to construct the `id` field in a way so that the `deduper` understand what is updated or not, but I want to do that on a certain property.

Question how?

**2. REST hook**
As i have understand, it is available for `CLI` integrations, but `REST hooks` are legacy and not recommended, but also see that it is mentioned and there is an example app in the new documentation https://github.com/zapier/zapier-platform-example-app-rest-hooks

so question is, is it really recommended? I'm trying to do it now a new app built by the CLI.

Am I making my self clear ?

Can someone shed some light?

**NOTE**
the slack channel is not working !

**Comment by xavdid** [comment]
Hi there! 

1. Update triggers are tough to do well. it's hard for users to successfully act on a property updating, since it's tough to communicate what updated. Unless you can think of a really clear use case, i'd avoid making one.
2. REST hooks are _not_ legacy and are currently the best way to create new triggers. Implement them if you're able. Where are you reading that they're legacy?
3. We recently updated the slack join link and I thought I had updated it everywhere. Where are  you seeing the broken one? In any case, [the readme](https://github.com/zapier/zapier-platform-cli#get-help) has a working one.

**Comment by mnsami** [comment]
hey @xavdid 

**Outdated slack channel**
For the outdated slack channel link, i got it from here => https://zapier.com/developer/documentation/v2/get-help/#join-us-in-slack

**REST hooks**
I think i was confused between static hooks and webhooks in general :)

Thanks for your answer :)

**Comment by xavdid** [comment]
Thanks for the flag, i've updated the page. ​Let me know if you've got any other questions!
