### ISSUE TITLE
Add push/promote hook

### ISSUE THREAD

**Issue by rebecca-ghazali** [zapier/zapier-platform-cli#416]
## What would you like to change?
It would be really nice to be able to define a "pre-push" or "pre-promote" hook in a CLI app. A developer could add some code there that would run before `zapier push` or `zapier promote` respectively. 

Use case: for an app that has both a Sandbox and Production environment - we'd like to make sure that the Sandbox environment is used for all testing and the Production environment is used for the live, promoted app. If there was this hook, I could add some code that would check that the environment variables are set to "PROD" before a promote to prevent someone from unwittingly pushing a version of the app live with the sandbox environment variables set.

**Comment by xavdid** [comment]
great suggestion! The easiest way to do this right now is to put those CLI operations in the `package.json` (`"zapier-promote"`) and use [scripts](https://docs.npmjs.com/misc/scripts) to  run those checks as needed (using something like `"prezapier-promote"`). Given that that's a pretty easy workaround, this probably won't be prioritized at this point (but we can leave it open).

The biggest issue to the above is if someone wasn't aware of the scripts and ran `promote` anyway. We could totally look into a way to have the CLI fail the operation if there's a matching `npm` script to ensure everyone goes through the script instead of the command. Happy to go through the use cases there with y'all!

**Comment by xavdid** [comment]
given there's a workaround, we probably won't add specific code for this. it sounds like y'all have something worked out though!
