### ISSUE TITLE
Improve RESTHook Example or Docs

### ISSUE THREAD

**Issue by kieraneglin** [zapier/zapier-platform-cli#76]
The RESTHook example is fine to get started, but I think it could have some extra information.

For instance, I'm working with a legacy codebase.  When you create a webhook, all events go to the URL you've provided.  You can't subscribe to just one event.

With this in mind, I've created a RESTHook-style controller in our app.  You can preform CRUD actions on webhooks, but you still get subscribed to every event.  However, each event has it's name in the response, like so:

```javascript
{
  "event": "user.create",
  "id": 0,
  // ...
}
```

In short, here's what I'm wondering:

- What is the preferred way to filter events so that each trigger only responds to the appropriate event?  I wouldn't want the `order.create` trigger firing on `user.update`.
- Is there a setter for `bubdle.targetUrl`? If my webhook broadcasts on any event, it would be best to subscribe a trigger to an existing webhook instead of making a new, redundant webhook each time.  I guess I'm looking to create an `upsert`-style function for `bundle.targtUrl`

I've looked in the examples and the docs, but I couldn't find anything that touches on this.  Any advice or links are appreciated!  I'd also be happy to make a PR with updated docs if I sort this out.

Thank you!

**Comment by bcooksey** [comment]
@kieraneglin If the hooks we get are for any event, you can have your `perform` function for the Trigger do the filter and only return a result if the event is of the correct type.

As for the `targetUrl`, we actually prefer to get the duplicate hooks for now. It ends up being much easier to manage that way. The explicit subscribe/unsubscribe calls are traceable by both ends, so it is clear what the expected state is. Internally, it helps us since we know when it is safe to make the unsubscribe call (any time a Zap is turned off).

**Comment by kieraneglin** [comment]
Thanks for the info!  Is there a preferred method to stop a `perform` function?  Or will `return false;` suffice?

**Comment by bryanhelmig** [comment]
`return []` will work.

**Comment by kieraneglin** [comment]
Thank you!
